# Changing from 1D array to 2D array in two different ways

You will encounter these two different methods converting 1D array to 2D array.

In [1]:
import numpy as np
import pandas as pd

Method 1

In [2]:
series = np.array([1,2,3,4,5,6,7,8,9,10])
series

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
series2D_col = series.reshape(-1,1)
series2D_col

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [4]:
series2D_row = series.reshape(1,-1)
series2D_row

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

Method 2

In [5]:
ser = np.arange(10)

In [6]:
ser

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
ser2D_col = ser[:, np.newaxis]
ser2D_col

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [8]:
ser2D_row = ser[np.newaxis, :]
ser2D_row

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])